[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "barcode/version.py"
version_scheme = "post-release"

[tool.black]
target-version = ['py37']

[tool.ruff]
select = [
    "E",
    "F",
    "W",
    "B0",
    "I",
    "UP",
    "N",
    "C4",
    "PT",
    "SIM",
    "TID",
]
target-version = "py37"

[tool.ruff.isort]
force-single-line = true
